### ISSUE TITLE
Compatible with Mac OS and Linux

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/Neuropsydia.py#10]
It would be great.

**Comment by DominiqueMakowski** [comment]
With mac it seems to work, however there might be an issue with the cvxopt package used for signal processing... further checking is required

**Comment by hndr91** [comment]
go/nogo task example running well on my mac v10.11

**Comment by cMadan** [comment]
@hndr91 - What mac hardware did you use?

**Comment by hndr91** [comment]
I'm using macpro 13 model mid-2012 running on el capitan @cMadan

**Comment by cMadan** [comment]
Hmm, I would've guessed the issue was related to my hardware being older, but it's the other way around... Macbook Pro 15", Late 2013, also El Capitan

**Comment by DominiqueMakowski** [comment]
@cMadan As neuropsydia is built on top of pygame, does this minimal pygame code works?

```python
import pygame
from pygame.locals import *

pygame.init()


screen = pygame.display.set_mode((640, 480))

pygame.draw.rect(screen, (128, 128, 128), (0, 0, 20, 20))
pygame.draw.rect(screen, (0, 128, 255), (40, 200, 30, 20))
pygame.draw.rect(screen, (255, 255, 0), (200, 20, 20, 80))

pygame.display.update()

pygame.time.wait(5000)
pygame.display.quit()
```
It should draw 3 rectangles on a screen, wait for 5 s and then quit.

**Comment by hndr91** [comment]
maybe my [gist](https://gist.github.com/hndr91/9eb42784aa0e65bac778d3f0df7ff3e6) can be helpful. I forgot, maybe I had problem with pygame too back then.

**Comment by cMadan** [comment]
Minimal pygame does work fine

**Comment by DominiqueMakowski** [comment]
Update: it worked on MacOS Yosemite.

Installation steps were:
1) install anaconda with python 3.6
2) open macOS terminal
3) (run `source activate root`, altough I'm not sure about that step, better try first without it)
4) run `pip install neuropsydia`

**Comment by jbcoffin** [comment]
Neuropsydia.py doesn't work with linux (Ubuntu 20.04.2 LTS).
pygame is ok

```
import neuropsydia as n
AttributeError: module 'ctypes' has no attribute 'windll'
```
